POST http://localhost:3000/api/blogs/
Content-Type: application/json

{
    "title": "Fullstack Open",
    "author": "Matti Luukkainen",
    "url": "https://fullstackopen.com/en",
    "likes": "100000",
    "userId": "67a4e0fe1a8c37bf1cf4b72a"
}