DELETE http://localhost:3000/api/blogs/67a9e8cec2a5ab3c7156016f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3YTRlMTE2MWE4YzM3YmYxY2Y0YjcyYyIsImlhdCI6MTczOTE4MTg2Nn0.Pc_LvSZyG62feZxb8PNTFiw9SWORg2xGFkKTm_JA1eA