POST http://localhost:3000/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3YTRlMTE2MWE4YzM3YmYxY2Y0YjcyYyIsImlhdCI6MTczOTE4MTg2Nn0.Pc_LvSZyG62feZxb8PNTFiw9SWORg2xGFkKTm_JA1eA


{
    "title": "Authentication and Authorization in Node.js",
    "author": "Pawan Kumar",
    "url": "https://codewithpawan.medium.com/authentication-and-authorization-in-node-js-a-comprehensive-guide-2755b57dce27",
    "likes": "164"
}