POST http://localhost:3000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3R1c2VyIiwiaWQiOiI2NzlmZDkxMjZhYWMxMDUxYzI3MTIzMjkiLCJpYXQiOjE3Mzg1MjkxNTF9.2HCKK6t6EnlPCOEGtKorM1xa5KLB9ryrD-oxFKYPHT4

{
    "content": "using JSON web tokens is easy.",
    "important": true
}